version: '3.3'

services:
  # Service pour le serveur Node.js avec Socket.IO
  socket-io:
    build:
      context: ./back # Répertoire contenant le Dockerfile du serveur Socket.IO
    ports:
      - "3001:3001"  # Mapping du port local vers le port du conteneur
    networks:
      - app-network
    volumes:
      - socket-data:/usr/src/app/data/

  # Service pour l'application React
  react-app:
    build:
      context: ./front # Répertoire contenant le Dockerfile de l'application React
    ports:
      - "80:80"  # Mapping du port local vers le port du conteneur Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  socket-data: