# Utilise une image officielle Node.js comme image de base
FROM node:18.19.1

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers de package (package.json et package-lock.json) dans le répertoire de travail
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Copier le reste des fichiers de l'application dans le conteneur
COPY . .

# Exposer le port sur lequel l'application écoute (par défaut 3000)
EXPOSE 3001

# Commande pour démarrer le serveur socket.io
CMD ["npm", "run", "start"]