# Utiliser une image de base Node.js pour construire l'application
FROM node:18.19.1 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du projet dans le conteneur
COPY . .

# Ca démarre
CMD ["npm", "run", "start"]
