# Utiliser une image de base Node.js pour construire l'application
FROM node:18.19.1 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du projet dans le conteneur
COPY . .

# Construire l'application pour la production
RUN npm run build

# Utiliser une image Nginx pour servir les fichiers construits
FROM nginx:alpine

# Copier le build React depuis l'image précédente
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port sur lequel Nginx écoute (par défaut, c'est le port 80)
EXPOSE 80

# Lancer Nginx en mode premier plan
CMD ["nginx", "-g", "daemon off;"]
